version: "3.3"

services:
  blockchain:
    image: node:lts-alpine
    ports:
      - "8545:8545"
    volumes:
      - ../blockchain:/home/node/blockchain
    user: node
    working_dir: /home/node/blockchain
    command:
      - "npx"
      - "hardhat"
      - "node"


  frontend:
    image: node:lts-alpine
    ports:
      - 3000:3000
    volumes:
      - ../frontend:/home/node/frontend
    user: node
    working_dir: /home/node/frontend
    command:
      - "npm"
      - "run"
      - "dev"
